
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
  -name: libs
    command: pip install selenium
      echo selenium

vscode:
  extensions:
    - github.vscode-pull-request-github
    - ms-python.python
