
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
      pip install selenium

vscode:
  extensions:
    - github.vscode-pull-request-github
    - ms-python.python
